export const body = `Patent box relief UK gives qualifying companies a significant tax incentive by taxing profits earned from patented inventions at a lower rate. This guide explains who can claim, what counts as qualifying IP profits, how the calculation works and the practical steps to make a compliant claim.

## What is patent box relief and why it matters

Patent box relief is a targeted tax relief that allows UK companies to apply a lower rate of corporation tax to profits derived from patented inventions and certain related intellectual property. The relief is designed to encourage companies to exploit, retain and commercialise IP in the UK. In practice, successful claims can reduce the effective tax rate on those profits to 10%, often described as a form of IP corporation tax relief.

For many small and medium sized companies with genuine patent-protected products or processes, the patent box can deliver material cash tax savings – but the rules are specialised and require careful record keeping and calculation of qualifying IP profits.

## Who can claim patent box relief UK

To claim patent box relief a company must meet several basic eligibility conditions:

- Be a UK resident company liable to corporation tax.
- Have relevant profits arising from a qualifying patented invention.
- Own the patent or have an exclusive licence to exploit the patent in the UK and EEA where conditions allow.
- Carry on a trade that exploits the patented invention or licence income from the patent.

Qualifying patents are normally granted patents effective in the UK – this includes UK-granted patents and European patents validated in the UK. There are also rules for related rights in some territories. For full details of qualifying IP and patent requirements see HMRC guidance on GOV.UK: https://www.gov.uk/guidance/patent-box.

## What counts as qualifying IP profits

Understanding what counts as qualifying IP profits is central to claiming the relief. Qualifying IP profits are the profits attributable to the exploitation of a qualifying patented invention. That can include:

- Profits from the sale of patented products.
- Profits from manufacturing a patented process.
- Royalty or licensing income from the patented rights.
- A share of profits where the company sells a product incorporating a qualifying patent.

Not all profits of the company will automatically qualify. You must identify and separate the portion of your overall profit that arises from the relevant IP activities. This often involves apportioning income and costs between patented and non-patented activities and making adjustments under the Patent Box computation rules.

## How the patent box tax calculation works – an overview

The Patent Box calculation can be complex. HMRC sets out a multistep approach to determine the amount of profit that can benefit from the 10% tax rate. The broad stages are:

1. Identify the relevant IP and the relevant IP income.
2. Calculate the relevant IP profits before Patent Box deductions.
3. Deduct any relevant IP expenditure and apply apportionments for non-qualifying items.
4. Apply the nexus fraction to separate profits linked to your own qualifying R&D from profits linked to externally contracted R&D.
5. Apply the Patent Box tax rate to the qualifying share of profits.

Below are the steps explained in more practical detail.

### Step 1 – identify your qualifying patents and relevant IP income

Make a list of the patents you own or exclusively licence and document how each patent is exploited in your trade. For each patent consider sources of income such as product sales, licence fees or royalties. If a product uses multiple patents or non-patented features, you will need to apportion income accordingly.

### Step 2 – calculate the relevant IP profits before adjustments

Start from the profits of the trade that are attributable to the relevant IP. Typical adjustments include:

- Excluding profits that arise from non-patented elements of the product.
- Adjusting for any routine returns for manufacturing or distribution activities.
- Including certain licence income and related costs.

HMRC provides detailed rules on what to include and exclude. The goal is to arrive at a profit figure that reasonably represents the return generated by the qualifying IP.

### Step 3 – make statutory deductions and apply notional deductions

Once you have the relevant IP profit, you must deduct any qualifying IP expenditure such as direct costs of exploiting the IP. Notional deductions may also be required to prevent double relief where other incentives apply.

### Step 4 – apply the nexus fraction

The nexus fraction is a key part of post-2016 Patent Box rules and ties the relief to genuine R&D activity. It determines the proportion of relevant IP profits that can be claimed based on how much of the innovation work was done by the claiming company versus contracted-out or acquired from third parties.

Factors that increase your nexus fraction include:

- Higher qualifying R&D expenditure carried out by the company.
- Ownership of the R&D results and relevant IP.

Contracted-out R&D or purchase of IP can reduce the fraction. The precise calculation requires allocating qualifying expenditure between patents and other activities and then applying the statutory formula.

### Step 5 – tax at the Patent Box rate

After these calculations you arrive at the qualifying amount of profit. That amount is taxed at the Patent Box rate – 10% – rather than the company’s usual corporation tax rate, creating the core benefit of the regime.

## Worked example (simple illustration)

This is a simplified example to show mechanics, not a full statutory calculation.

- Company A makes gross profit of 600,000 from a product where 400,000 is attributable to patented features.
- After allowable deductions and adjustments, the relevant IP profit is agreed as 350,000.
- The nexus fraction based on the company’s R&D is 75% so qualifying IP profits become 262,500 (350,000 x 75%).
- Those 262,500 are taxed at 10% under Patent Box rather than the usual corporation tax rate, generating a tax charge of 26,250 instead of a higher figure at the normal rate.

This example hides many of the statutory adjustments but illustrates the flow you should expect when assessing the likely benefit.

## Patent box and R&D tax credits – how they interact

Patent box relief interacts closely with R&D tax reliefs. The more qualifying R&D a company carries out itself, the greater the nexus fraction and usually the higher the share of profits that can benefit from Patent Box. Conversely, if key R&D is outsourced or you buy-in IP, the nexus fraction is lower and the benefit reduces.

Key points:

- R&D tax credits and Patent Box are separate reliefs and can both be claimed, subject to the normal rules.
- Ensure you keep distinct records for R&D claims and Patent Box calculations – HMRC expects clear evidence linking R&D activities to patents.
- Speak to a specialist if you both claim R&D credits and plan to use Patent Box – the interactions can be operationally complex but beneficial.

## Practical steps to claim patent box relief UK

1. Review your IP portfolio and confirm which patents are granted and qualifying.
2. Map sales, licences and products to specific patents and identify the IP-related income streams.
3. Gather R&D records, contracts, invoices and payroll evidence to support the nexus calculation.
4. Carry out or instruct a specialist to perform the detailed Patent Box computation.
5. Make an election to enter the Patent Box for the accounting period in your company tax return and include the supporting calculation. There are specific reporting requirements – see HMRC guidance at GOV.UK for exact procedural steps.
6. Keep documentary evidence and calculations for at least the period HMRC requires in case of queries.

Companies often find it efficient to work with an accountant, tax adviser or a fractional CFO to prepare a robust claim and ensure the tax treatment is applied correctly. If you need help with this analysis, our [Fractional CFO](/services#fractional-cfo) and [Statutory Accounts & Tax](/services#statutory-accounts-tax) services can support your claim. For timely bookkeeping and to capture the source data you will need, consider [Bookkeeping & Xero](/services#bookkeeping-xero).

## Record keeping and evidence HMRC expects

HMRC will expect clear evidence to support a Patent Box claim. Maintain:

- Patent documentation including grant numbers and filing dates.
- Sales and licence agreements connected to the patent.
- R&D project records, timesheets, payroll and supplier invoices for qualifying R&D.
- Calculations showing how you apportioned profits and applied the nexus fraction.
- Board minutes or management reports approving the Patent Box election.

Poor record keeping is one of the most common reasons HMRC challenges claims. Accurate records also make the computation quicker and reduce the risk of penalties.

## Common pitfalls to avoid

- Claiming without evidence linking R&D work to the patent.
- Ignoring the nexus rules and assuming 100% of patented product profit qualifies.
- Failing to make or record the necessary election in the company tax return.
- Treating Patent Box relief as a simple headline rate change without adjusting accounts or cash flow forecasts.

## Is patent box relief right for your business?

The Patent Box can be highly valuable for companies with genuine patent-protected inventions and substantial profits from exploiting them. It is less likely to be worth the administrative burden for companies with minimal patent-related income or small losses.

Consider these questions:

- Do you own or exclusively licence a qualifying patent that is already granted?
- Can you demonstrate a clear link between R&D activities and the patent?
- Are the tax savings likely to exceed compliance costs?

If the answer is yes to the first two and possibly yes to the third, a detailed assessment is worthwhile.

## Dealing with HMRC enquiries

If HMRC queries your Patent Box claim they will typically want to see the calculations and the evidence tying R&D to the patent. Engage early with HMRC, provide the requested documentation promptly and consider specialist tax support to handle technical points.

## Accounting, management reporting and cash flow planning

Patent Box claims affect your tax computations and cash flow. You will need to:

- Reflect any reduced tax liability in cash flow forecasts and forecasts for the year.
- Ensure company tax returns and statutory accounts reconcile with the tax computations.
- Factor the relief into management reporting so directors and investors understand its impact.

If you need help incorporating Patent Box effects into forecasting or board reporting, our [Management Reporting](/services#management-reporting) and [Fractional CFO](/services#fractional-cfo) offerings can help you plan and present the impact clearly.

## Time limits and administrative deadlines

Claims must be made in compliance with HMRC rules and filing deadlines. The election to enter Patent Box is made in the company tax return for the accounting period concerned. There are time limits for amending returns and making late claims, so do not delay once you believe you have a qualifying position. Refer to HMRC guidance for the exact deadlines and procedural steps: https://www.gov.uk/guidance/patent-box.

## Common questions about ownership and licences

- Companies must generally own the patent or have an exclusive licence to exploit it for the relief to apply.
- Non-exclusive licences or simple manufacturing contracts do not normally qualify in the same way as ownership or exclusive exploitation.

If your IP is group owned or licensed between related parties, the allocation of profits and the link to R&D must be carefully constructed. Tax advisers can help structure arrangements that meet the statutory tests.

## When patent box relief may not be worth pursuing

- If patent-related profits are tiny or intermittent the compliance burden may outweigh the tax benefit.
- If most R&D was outsourced or you acquired the IP from third parties the nexus fraction may be low reducing the value of the relief.
- If you operate at a loss or just above break-even the immediate cash benefit may be minimal.

A short feasibility study usually clarifies whether a full claim is justified.

## UK tax and legal accuracy

This article is for informational purposes only and does not constitute professional tax or financial advice. Please speak to a qualified accountant before taking action. Relevant tax year: 2026/27.

For definitive HMRC guidance and the legal text consult GOV.UK: https://www.gov.uk/guidance/patent-box.

## Frequently asked questions

**Q: What is the effective tax rate under the Patent Box?**

A: Patent Box relief reduces the effective tax rate on qualifying IP profits to 10%.

**Q: Do I need to own the patent to claim the relief?**

A: You normally need to own the patent or hold an exclusive licence to exploit it in the UK to claim Patent Box relief. The details vary, so check the specific HMRC rules.

**Q: How does Patent Box interact with R&D tax credits?**

A: They are separate reliefs. The amount of R&D carried out by the claimant affects the nexus fraction used in Patent Box calculations. It is common to claim both where eligible, but you should maintain clear records.

**Q: Can I claim Patent Box for historic accounting periods?**

A: There are time limits and rules around amending past returns and making elections. If you think you have missed a claim, consult HMRC guidance and a tax adviser promptly.

**Q: Does buying a patent from another company affect my claim?**

A: Purchasing IP can reduce the nexus fraction and therefore reduce the amount of profit eligible under the Patent Box. The rules treat acquired IP differently from IP developed in-house.

## Summary and next steps

Patent box relief UK can significantly lower the tax on profits that arise from patented inventions, but it requires careful identification of qualifying IP profits, application of the nexus rules and robust record keeping. If you own or exploit patents and you make taxable profits from them, it is worth assessing whether the Patent Box could reduce your corporation tax liability.

Next steps:

- Conduct a quick feasibility review of your patents and associated income.
- Gather R&D records and sales/licence data.
- Speak to an accountant experienced in Patent Box calculations.

If you would like expert help assessing eligibility or preparing a compliant claim, book a discovery call with Figures: [book a discovery call](/). We can support the technical calculation, audit-proof documentation and explain how the relief affects your cash flow and accounts.`;
